/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ilyane.java;

import java.util.Arrays;

import org.bson.Document;

//import com.mongodb.ConnectionString;
import com.mongodb.MongoClientSettings;
import com.mongodb.ServerAddress;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.MongoCollection;

public class App {
    public String getGreeting() {
    	
       return "Hello world.";
    } 

    public static void main(String[] args) {  
        System.out.println(new App().getGreeting());
        
        String database = "";
        String host = "";
        int port = 0;
    	
        for(int i = 0 ; i < args.length ; i++)
        {
        	if (args[i].equals("--db"))
        	{
                if (i + 1 < args.length && !args[i + 1].startsWith("--"))
                {
                  database = args[i+1];
                }
                else
                {
                  throw new Exception("--db not defined");
                }
            }
        	
        	if (args[i].equals("--host"))
        	{
                if (i + 1 < args.length && !args[i + 1].startsWith("--"))
                {
                	host = args[i+1];
                }
                else
                {
                	throw new Exception("--host not defined");
                }
            }
        	
        	if (args[i].equals("--port"))
        	{
                if (i + 1 < args.length && !args[i + 1].startsWith("--"))
                {
                	String portString = args[i+1];
                	port = Integer.parseInt(portString);
                	
                }
                else
                {
                	throw new Exception("--port not defined");
                }
            }
        }
        
        
        public static MongoClient getMongoClient(final String host, final int port)
        MongoClient mongoClient = MongoClients.create(
                MongoClientSettings.builder()
                        .applyToClusterSettings(builder ->
                                builder.hosts(Arrays.asList(new ServerAddress(host, port))))
                        .build());
        return mongoClient;
       
        //MongoClient mongoClient = MongoClients.create();
    	//MongoClient mongoClient = MongoClients.create("mongodb://hostOne:27017");
    	//MongoDatabase database = mongoClient.getDatabase("database");
    	//MongoCollection<Document> collection = database.getCollection("test");
    	 
    }
}
